swedbank:
  service_url: https://www.swedbank.ee/banklink
  return_url: http://test.local/swedbank
  cancel_url: http://test.local/swedbank
  login: dealer
  file_cert: ../certificates/bank.pub
  file_key: ../certificates/dealer.key
  key_secret: foobar
  encoding: UTF-8
  snd_id: sender
