swedbank:
  service_url: https://www.swedbank.ee/banklink
  return_url: http://test.local/swedbank
  cancel_url: http://test.local/swedbank
  login: dealer
  file_cert: ../certificates/bank.crt
  file_key: ../certificates/dealer.key
  key_secret: foobar
  encoding: UTF-8
  snd_id: sender

seb:
  service_url: https://www.seb.ee/banklink
  return_url: http://test.local/seb
  cancel_url: http://test.local/seb
  login: dealer
  file_cert: ../certificates/seb_test_pub.crt
  file_key: ../certificates/dealer.key
  key_secret: foobar
  encoding: UTF-8
  snd_id: sender

nordea:
  service_url: https://netbank.nordea.com/pnbepaytest/epayn.jsp
  return_url: http://test.local/nordea
  reject_url: http://test.local/nordea
  cancel_url: http://test.local/nordea
  key: ../certificates/nordea_test_priv
  rcv_id: '12345678'
  language: '4'
  confirm: 'YES'
  keyvers: '0001'
