swedbank:
  service_url: https://www.swedbank.ee/banklink
  return_url: http://test.local/return
  cancel_url: http://test.local/cancel
  snd_id: dealer
  file_cert: ../certificates/pangalink_swedbank_bank_cert.pem
  file_key: ../certificates/pangalink_swedbank_user_key.pem
  key_secret: foobar
  encoding: UTF-8
  wtf: not

seb:
  service_url: https://www.seb.ee/banklink
  sign_algorithm: 'sha256'
  verification_algorithm: 'sha1'
