swedbank:
  service_url: https://www.swedbank.ee/banklink
  return_url: http://test.local/return
  cancel_url: http://test.local/cancel
  snd_id: dealer
  file_cert: ../certificates/bank.pub
  file_key: ../certificates/dealer.key
  key_secret: foobar
  encoding: ISO-8859-4
  wtf: not

seb:
  service_url: https://www.seb.ee/banklink
